# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDOSacrNoDOwsTHbY9gOhN2syLyUrOre
"""

import random
import numpy as np
import torch

def set_seed(seed_value=42):
    """Set seeds for reproducibility."""
    random.seed(seed_value)
    np.random.seed(seed_value)
    torch.manual_seed(seed_value)
    torch.cuda.manual_seed_all(seed_value)
    # For deterministic algorithms, if you need them
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# Call the function to set the seed
set_seed(42)
print("Random seed set to 42 for reproducibility.")

mkdir -p ~/.kaggle && echo KGAT_fe074232bef2df99810ea8dccbd20756 > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token

!kaggle datasets download -d ipateam/segmentation-of-nuclei-in-cryosectioned-he-images
!kaggle datasets download -d tuanledinh/monuseg2018

!unzip segmentation-of-nuclei-in-cryosectioned-he-images.zip -d cryonuseg
!unzip monuseg2018.zip -d monuseg

import os

print(os.listdir("cryonuseg"))
print(os.listdir("monuseg"))

img_dir = "cryonuseg/tissue images"
mask_dir = "/content/cryonuseg/Annotator 1 (biologist second round of manual marks up)/Annotator 1 (biologist second round of manual marks up)/label masks"

images = sorted(os.listdir(img_dir))
masks = sorted(os.listdir(mask_dir))

print("IMAGE:", images[:5])
print("MASK :", masks[:5])

print(os.listdir("/content/monuseg/kmms_training/kmms_training/images"))
print(os.listdir("/content/monuseg/kmms_training/kmms_training/masks"))
print(os.listdir("/content/monuseg/kmms_test/kmms_test/masks"))
print(os.listdir("/content/monuseg/kmms_test/kmms_test/images"))

import os

mask_dir = "/content/monuseg/kmms_training/kmms_training/masks"

for f in os.listdir(mask_dir):
    if " .png" in f:
        os.rename(
            os.path.join(mask_dir, f),
            os.path.join(mask_dir, f.replace(" .png", ".png"))
        )

import os

mask_dir = "/content/monuseg/kmms_test/kmms_test/masks"

for f in os.listdir(mask_dir):
    if " .png" in f:
        os.rename(
            os.path.join(mask_dir, f),
            os.path.join(mask_dir, f.replace(" .png", ".png"))
        )

!kaggle competitions download -c histopathologic-cancer-detection

!unzip -q histopathologic-cancer-detection.zip -d pcam

print(os.listdir("pcam"))

!pip install -q segmentation-models-pytorch albumentations timm

#load libraries
import os
import cv2
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split

import albumentations as A

import segmentation_models_pytorch as smp
import torchvision.models as models

from sklearn.metrics import roc_auc_score, f1_score

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from glob import glob
from tqdm import tqdm

"""Inspection of datasets: cryonuseg, monuseq and pcam"""

def scan_dataset(path, exts=("png", "jpg", "jpeg", "tif", "tiff"), limit=500):

    image_paths = []

    for ext in exts:
        image_paths.extend(
            glob(os.path.join(path, f"**/*.{ext}"), recursive=True)
        )

    sizes = []
    corrupted = []

    for p in tqdm(image_paths[:limit]):
        try:
            img = cv2.imread(p, cv2.IMREAD_UNCHANGED)

            if img is None:
                corrupted.append(p)
                continue

            # handle grayscale vs RGB vs multi-channel TIFF
            if len(img.shape) == 2:
                h, w = img.shape
            else:
                h, w = img.shape[:2]

            sizes.append((h, w))

        except:
            corrupted.append(p)

    sizes = np.array(sizes)

    return {
        "total_images": len(image_paths),
        "corrupted": len(corrupted),
        "avg_height": float(np.mean(sizes[:, 0])) if len(sizes) else 0,
        "avg_width": float(np.mean(sizes[:, 1])) if len(sizes) else 0,
        "height_std": float(np.std(sizes[:, 0])) if len(sizes) else 0,
        "width_std": float(np.std(sizes[:, 1])) if len(sizes) else 0,
    }

cryo_stats = scan_dataset("/content/cryonuseg")
monu_stats = scan_dataset("/content/monuseg")
pcam_stats = scan_dataset("/content/pcam")

print("CryoNuSeg:", cryo_stats)
print("MoNuSeg:", monu_stats)
print("PCam:", pcam_stats)

cryo_stats_images = scan_dataset("/content/cryonuseg/tissue images")
cryo_stats_masks = scan_dataset("/content/cryonuseg/Annotator 1 (biologist second round of manual marks up)/Annotator 1 (biologist second round of manual marks up)/label masks")

monu_stats = scan_dataset("/content/monuseg")
pcam_stats = scan_dataset("/content/pcam")

print("CryoNuSeg images:", cryo_stats_images)
print("CryoNuSeg masks:", cryo_stats_masks)
print("MoNuSeg:", monu_stats)
print("PCam:", pcam_stats)

"""visualizing images in all datasets through show samples"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from glob import glob

def show_samples(path, n=9, exts=("png", "jpg", "jpeg", "tif", "tiff")):

    imgs = []

    # collect all image types properly
    for ext in exts:
        imgs.extend(
            glob(os.path.join(path, f"**/*.{ext}"), recursive=True)
        )

    if len(imgs) == 0:
        print("No images found in:", path)
        return

    samples = np.random.choice(imgs, min(n, len(imgs)), replace=False)

    plt.figure(figsize=(8, 8))

    for i, p in enumerate(samples):
        img = cv2.imread(p, cv2.IMREAD_UNCHANGED)

        if img is None:
            continue

        # handle grayscale vs RGB
        if len(img.shape) == 2:
            img_rgb = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
        else:
            img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        plt.subplot(3, 3, i + 1)
        plt.imshow(img_rgb)
        plt.axis("off")

    plt.tight_layout()
    plt.show()

show_samples("/content/cryonuseg")
show_samples("/content/monuseg")
show_samples("/content/pcam")

"""visualizing images and masks in pairs only cryonuseg and monuseg"""

# visualizing images and masks in pairs
import os
import cv2
import matplotlib.pyplot as plt
from glob import glob

def show_random_pair(image_dir, mask_dir, n=3):

    img_paths = glob(os.path.join(image_dir, "*"))

    if len(img_paths) == 0:
        print("No images found:", image_dir)
        return

    import random
    samples = random.sample(img_paths, min(n, len(img_paths)))

    plt.figure(figsize=(10, 3*n))

    for i, img_path in enumerate(samples):

        filename = os.path.basename(img_path)

        # try to find matching mask
        mask_path = None
        for ext in ["png", "jpg", "tif", "tiff"]:
            candidate = os.path.join(mask_dir, filename.replace(".png", f".{ext}")
                                                   .replace(".jpg", f".{ext}")
                                                   .replace(".tif", f".{ext}"))
            if os.path.exists(candidate):
                mask_path = candidate
                break

        img = cv2.imread(img_path)

        if img is None:
            continue

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        plt.subplot(n, 2, 2*i+1)
        plt.imshow(img)
        plt.title("Image")
        plt.axis("off")

        if mask_path and os.path.exists(mask_path):
            mask = cv2.imread(mask_path, 0)
            plt.subplot(n, 2, 2*i+2)
            plt.imshow(mask, cmap="gray")
            plt.title("Mask")
        else:
            plt.subplot(n, 2, 2*i+2)
            plt.text(0.5, 0.5, "No Mask Found", ha="center", va="center")
            plt.axis("off")

    plt.tight_layout()
    plt.show()

show_random_pair(
    "/content/cryonuseg/tissue images",
    "/content/cryonuseg/Annotator 1 (biologist second round of manual marks up)/Annotator 1 (biologist second round of manual marks up)/label masks"
)

#masks of annotator 2
show_random_pair(
    "/content/cryonuseg/tissue images",
    "/content/cryonuseg/Annotator 2 (bioinformatician)/Annotator 2 (bioinformatician)/label masks"
)

show_random_pair(
    "/content/monuseg/kmms_training/kmms_training/images",
    "/content/monuseg/kmms_training/kmms_training/masks"
)

"""Visualizing pcam data"""

def show_pcam_samples(train_dir, label_csv):
    import pandas as pd
    import random

    df = pd.read_csv(label_csv)

    samples = df.sample(6)

    plt.figure(figsize=(8,8))

    for i, row in enumerate(samples.itertuples()):

        img_path = os.path.join(train_dir, row.id + ".tif")
        img = cv2.imread(img_path)

        if img is None:
            continue

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        plt.subplot(3,2,i+1)
        plt.imshow(img)
        plt.title(f"Label: {row.label}")
        plt.axis("off")

    plt.tight_layout()
    plt.show()

show_pcam_samples(
    "/content/pcam/train",
    "/content/pcam/train_labels.csv"
)

"""visualizing random pairs in monuseg"""

import os
from glob import glob

def build_mask_dict(mask_dir):
    mask_paths = glob(os.path.join(mask_dir, "**/*.*"), recursive=True)

    mask_dict = {}

    for p in mask_paths:
        name = os.path.splitext(os.path.basename(p))[0]
        mask_dict[name] = p

    return mask_dict

import cv2
import random
import matplotlib.pyplot as plt

def show_random_pair_fixed(image_dir, mask_dir, n=3):

    mask_dict = build_mask_dict(mask_dir)
    img_paths = glob(os.path.join(image_dir, "*"))

    samples = random.sample(img_paths, min(n, len(img_paths)))

    plt.figure(figsize=(10, 3*n))

    for i, img_path in enumerate(samples):

        name = os.path.splitext(os.path.basename(img_path))[0]

        img = cv2.imread(img_path)
        if img is None:
            continue

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        mask_path = mask_dict.get(name, None)

        plt.subplot(n, 2, 2*i+1)
        plt.imshow(img)
        plt.title("Image")
        plt.axis("off")

        plt.subplot(n, 2, 2*i+2)

        if mask_path is not None:
            mask = cv2.imread(mask_path, 0)
            plt.imshow(mask, cmap="gray")
            plt.title("Mask")
        else:
            plt.text(0.5, 0.5, "NO MATCH", ha="center")
            plt.axis("off")

        plt.axis("off")

    plt.tight_layout()
    plt.show()

show_random_pair_fixed(
    "/content/monuseg/kmms_training/kmms_training/images",
    "/content/monuseg/kmms_training/kmms_training/masks"
)

"""**skip below** cleaning file names in monuseg"""

import os

def clean_filenames(folder):
    for f in os.listdir(folder):
        new = f.strip()
        if new != f:
            os.rename(
                os.path.join(folder, f),
                os.path.join(folder, new)
            )

print(os.listdir("/content/monuseg/kmms_training/kmms_training/images"))
print(os.listdir("/content/monuseg/kmms_training/kmms_training/masks"))
print(os.listdir("/content/monuseg/kmms_test/kmms_test/masks"))
print(os.listdir("/content/monuseg/kmms_test/kmms_test/images"))

clean_filenames("/content/monuseg/kmms_training/kmms_training/images")
clean_filenames("/content/monuseg/kmms_training/kmms_training/masks")
clean_filenames("/content/monuseg/kmms_test/kmms_test/masks")
clean_filenames("/content/monuseg/kmms_test/kmms_test/images")

from glob import glob
import os

def build_tcga_index(img_dir, mask_dir):

    imgs = glob(os.path.join(img_dir, "*.tif"))
    masks = glob(os.path.join(mask_dir, "*.png"))

    mask_dict = {os.path.splitext(os.path.basename(m))[0]: m for m in masks}
    img_dict = {os.path.splitext(os.path.basename(i))[0]: i for i in imgs}

    pairs = []

    for k in img_dict.keys():
        if k in mask_dict:
            pairs.append((img_dict[k], mask_dict[k]))

    return pairs

build_tcga_index("/content/monuseg/kmms_training/kmms_training/images", "/content/monuseg/kmms_training/kmms_training/masks")
build_tcga_index("/content/monuseg/kmms_test/kmms_test/images", "/content/monuseg/kmms_test/kmms_test/masks")

import os
from glob import glob
from collections import defaultdict

def normalize_name(path):
    """Extract clean filename stem"""
    return os.path.splitext(os.path.basename(path.strip()))[0]

def build_index(image_dir, mask_dir, exts=("png","tif","tiff","jpg","jpeg")):

    image_paths = []
    mask_paths = []

    for ext in exts:
        image_paths.extend(glob(os.path.join(image_dir, f"*.{ext}")))
        mask_paths.extend(glob(os.path.join(mask_dir, f"*.{ext}")))

    image_dict = defaultdict(list)
    mask_dict = defaultdict(list)

    for p in image_paths:
        image_dict[normalize_name(p)].append(p)

    for p in mask_paths:
        mask_dict[normalize_name(p)].append(p)

    return image_dict, mask_dict

def validate_pairs(image_dir, mask_dir):

    image_dict, mask_dict = build_index(image_dir, mask_dir)

    matched = []
    missing_masks = []
    orphan_masks = []

    for key in image_dict:

        if key in mask_dict:
            for img in image_dict[key]:
                for msk in mask_dict[key]:
                    matched.append((img, msk))
        else:
            missing_masks.append(image_dict[key])

    for key in mask_dict:
        if key not in image_dict:
            orphan_masks.append(mask_dict[key])

    print("✅ Total matched pairs:", len(matched))
    print("❌ Images without masks:", len(missing_masks))
    print("⚠️ Orphan masks:", len(orphan_masks))

    return matched, missing_masks, orphan_masks

monu_img = "/content/monuseg/kmms_training/kmms_training/images"
monu_mask = "/content/monuseg/kmms_training/kmms_training/masks"

monu_pairs, monu_missing, monu_orphans = validate_pairs(monu_img, monu_mask)

monu_img_test = "/content/monuseg/kmms_test/kmms_test/images"
monu_mask_test = "/content/monuseg/kmms_test/kmms_test/masks"

monu_test_pairs, _, _ = validate_pairs(monu_img_test, monu_mask_test)

def clean_pairs(pairs):
    return [(img, mask) for img, mask in pairs if img and mask]

os.listdir("/content/monuseg/kmms_test/kmms_test/images")
os.listdir("/content/monuseg/kmms_test/kmms_test/masks")

import os
import shutil
from glob import glob

def normalize(name):
    return name.strip()  # removes trailing/leading spaces

def get_files(folder, exts=("png","tif","tiff","jpg","jpeg")):
    files = []
    for ext in exts:
        files.extend(glob(os.path.join(folder, f"*.{ext}")))
    return files

def clean_and_split(image_dir, mask_dir,
                    clean_img_dir,
                    clean_mask_dir,
                    orphan_img_dir,
                    orphan_mask_dir):

    os.makedirs(clean_img_dir, exist_ok=True)
    os.makedirs(clean_mask_dir, exist_ok=True)
    os.makedirs(orphan_img_dir, exist_ok=True)
    os.makedirs(orphan_mask_dir, exist_ok=True)

    images = get_files(image_dir)
    masks = get_files(mask_dir)

    # normalize dictionary (stem → path)
    img_dict = {os.path.splitext(os.path.basename(f.strip()))[0]: f for f in images}
    mask_dict = {os.path.splitext(os.path.basename(f.strip()))[0]: f for f in masks}

    matched = 0
    orphan_images = 0
    orphan_masks = 0

    # 1. process images
    for k, img_path in img_dict.items():

        img_path_clean = img_path.strip()
        mask_path = mask_dict.get(k)

        if mask_path:  # valid pair
            matched += 1

            shutil.copy(img_path_clean, os.path.join(clean_img_dir, os.path.basename(img_path_clean)))
            shutil.copy(mask_path.strip(), os.path.join(clean_mask_dir, os.path.basename(mask_path)))

        else:  # orphan image
            orphan_images += 1
            shutil.copy(img_path_clean, os.path.join(orphan_img_dir, os.path.basename(img_path_clean)))

    # 2. process orphan masks
    for k, mask_path in mask_dict.items():
        if k not in img_dict:
            orphan_masks += 1
            shutil.copy(mask_path.strip(), os.path.join(orphan_mask_dir, os.path.basename(mask_path)))

    print("✅ Matched pairs:", matched)
    print("❌ Orphan images:", orphan_images)
    print("⚠️ Orphan masks:", orphan_masks)

clean_and_split(
    image_dir="/content/monuseg/kmms_test/kmms_test/images",
    mask_dir="/content/monuseg/kmms_test/kmms_test/masks",

    clean_img_dir="/content/monuseg_clean/test/images",
    clean_mask_dir="/content/monuseg_clean/test/masks",

    orphan_img_dir="/content/monuseg_clean/test/orphan_images",
    orphan_mask_dir="/content/monuseg_clean/test/orphan_masks"
)

os.listdir("/content/monuseg_clean/test/orphan_images")

os.listdir("/content/monuseg_clean/test/orphan_masks")

"""**skip above**

Stage 1
"""

import os
from glob import glob

def get_pairs(img_dir, mask_dir):

    img_paths = glob(os.path.join(img_dir, "*"))
    mask_paths = glob(os.path.join(mask_dir, "*"))

    img_dict = {os.path.splitext(os.path.basename(p))[0]: p for p in img_paths}
    mask_dict = {os.path.splitext(os.path.basename(p))[0]: p for p in mask_paths}

    pairs = []

    for k in img_dict:
        if k in mask_dict:
            pairs.append((img_dict[k], mask_dict[k]))

    return pairs

get_pairs("/content/cryonuseg/tissue images", "/content/cryonuseg/Annotator 1 (biologist second round of manual marks up)/Annotator 1 (biologist second round of manual marks up)/label masks")

# @title cryonuseg preprocessing
import os
import cv2
import numpy as np
from glob import glob

IMG_SIZE = 256

import os
from glob import glob

def get_name(path):
    return os.path.splitext(os.path.basename(path))[0]


def match_images_and_masks(img_dir, mask_dir, recursive=False):

    # Load paths
    img_paths = glob(os.path.join(img_dir, "*"))
    mask_paths = glob(os.path.join(mask_dir, "**", "*"), recursive=recursive)

    # Build dictionaries
    img_dict = {get_name(p): p for p in img_paths}
    mask_dict = {get_name(p): p for p in mask_paths}

    # Keys
    img_names = set(img_dict.keys())
    mask_names = set(mask_dict.keys())

    # Matches & mismatches
    matched = img_names.intersection(mask_names)
    only_imgs = img_names - mask_names
    only_masks = mask_names - img_names

    print("===================================")
    print(f"Total Images: {len(img_names)}")
    print(f"Total Masks : {len(mask_names)}")
    print(f"Matched Pairs: {len(matched)}")
    print(f"Unmatched Images: {len(only_imgs)}")
    print(f"Unmatched Masks: {len(only_masks)}")
    print("===================================\n")

    # Show some mismatches (debugging)
    if only_imgs:
        print("Example unmatched images:")
        for i, name in enumerate(list(only_imgs)[:10]):
            print("  ", name)

    if only_masks:
        print("\nExample unmatched masks:")
        for i, name in enumerate(list(only_masks)[:10]):
            print("  ", name)

    # Create paired lists
    img_list = []
    mask_list = []

    for name in matched:
        img_list.append(img_dict[name])
        mask_list.append(mask_dict[name])

    return img_list, mask_list


# ---------------- USAGE ----------------

img_dir = "/content/cryonuseg/tissue images"
mask_dir = "/content/cryonuseg/Annotator 1 (biologist second round of manual marks up)/Annotator 1 (biologist second round of manual marks up)/label masks"

img_list, mask_list = match_images_and_masks(img_dir, mask_dir, recursive=True)

print("\nExample pair:")
if len(img_list) > 0:
    print("Image:", img_list[0])
    print("Mask :", mask_list[0])

import cv2

test_mask = mask_list[0]
img = cv2.imread(test_mask, 0)

print("min:", img.min())
print("max:", img.max())
print("unique:", np.unique(img))

mask_path = mask_list[0]
from PIL import Image
import numpy as np

mask = np.array(Image.open(mask_path))
print("min:", mask.min())
print("max:", mask.max())
print("unique:", np.unique(mask))

import os
from glob import glob

img_dir = "/content/cryonuseg/tissue images"
mask_dir = "/content/cryonuseg/Annotator 1 (biologist second round of manual marks up)/Annotator 1 (biologist second round of manual marks up)/label masks"

img_paths = sorted(glob(os.path.join(img_dir, "*")))
mask_paths = sorted(glob(os.path.join(mask_dir, "**", "*"), recursive=True))

def get_name(p):
    return os.path.splitext(os.path.basename(p))[0]

mask_dict = {get_name(p): p for p in mask_paths}

paired_imgs = []
paired_masks = []

for img_path in img_paths:
    name = get_name(img_path)

    if name in mask_dict:
        paired_imgs.append(img_path)
        paired_masks.append(mask_dict[name])

print("Pairs:", len(paired_imgs))

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models

def align(x, ref):
    _, _, H, W = ref.shape
    return F.interpolate(x, size=(H, W), mode="bilinear", align_corners=False)

class CryoNuSegDataset(Dataset):

    def __init__(self, img_paths, mask_paths, img_size=256):
        self.img_paths = img_paths
        self.mask_paths = mask_paths
        self.img_size = img_size

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):

        img = cv2.imread(self.img_paths[idx])
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (self.img_size, self.img_size))
        img = img / 255.0

        # Use PIL to read the mask to ensure all values are preserved
        mask = np.array(Image.open(self.mask_paths[idx]))
        mask = cv2.resize(mask, (self.img_size, self.img_size),
                          interpolation=cv2.INTER_NEAREST)

        mask_bin = (mask > 0).astype(np.float32)

        kernel = np.ones((3, 3), np.uint8)
        boundary = cv2.dilate(mask_bin, kernel) - mask_bin

        img = torch.tensor(img, dtype=torch.float32).permute(2, 0, 1)
        mask_bin = torch.tensor(mask_bin, dtype=torch.float32).unsqueeze(0)
        boundary = torch.tensor(boundary, dtype=torch.float32).unsqueeze(0)

        return img, mask_bin, boundary

class ResNetUNet(nn.Module):

    def __init__(self):
        super().__init__()

        resnet = models.resnet34(weights="IMAGENET1K_V1")

        # correct encoder blocks
        self.layer0 = nn.Sequential(
            resnet.conv1,
            resnet.bn1,
            resnet.relu
        )  # 64 channels

        self.pool = resnet.maxpool
        self.layer1 = resnet.layer1  # 64
        self.layer2 = resnet.layer2  # 128
        self.layer3 = resnet.layer3  # 256
        self.layer4 = resnet.layer4  # 512

        # decoder
        self.up4 = nn.ConvTranspose2d(512, 256, 2, 2)
        self.dec4 = nn.Conv2d(512, 256, 3, padding=1)

        self.up3 = nn.ConvTranspose2d(256, 128, 2, 2)
        self.dec3 = nn.Conv2d(256, 128, 3, padding=1)

        self.up2 = nn.ConvTranspose2d(128, 64, 2, 2)
        self.dec2 = nn.Conv2d(128, 64, 3, padding=1)

        self.up1 = nn.ConvTranspose2d(64, 64, 2, 2)
        self.dec1 = nn.Conv2d(128, 64, 3, padding=1)

        self.up0 = nn.ConvTranspose2d(64, 32, 2, 2)
        self.dec0 = nn.Conv2d(96, 32, 3, padding=1)

        self.seg_head = nn.Conv2d(32, 1, 1)
        self.boundary_head = nn.Conv2d(32, 1, 1)

    def forward(self, x):

        # encoder (FIXED FLOW)
        x0 = self.layer0(x)          # 64
        x1 = self.layer1(self.pool(x0))  # 64
        x2 = self.layer2(x1)         # 128
        x3 = self.layer3(x2)         # 256
        x4 = self.layer4(x3)         # 512

        # decoder
        d4 = self.up4(x4)
        d4 = align(d4, x3)
        d4 = self.dec4(torch.cat([d4, x3], dim=1))

        d3 = self.up3(d4)
        d3 = align(d3, x2)
        d3 = self.dec3(torch.cat([d3, x2], dim=1))

        d2 = self.up2(d3)
        d2 = align(d2, x1)
        d2 = self.dec2(torch.cat([d2, x1], dim=1))

        d1 = self.up1(d2)
        d1 = align(d1, x0)
        d1 = self.dec1(torch.cat([d1, x0], dim=1))

        d0 = self.up0(d1)

        seg = torch.sigmoid(self.seg_head(d0))
        boundary = torch.sigmoid(self.boundary_head(d0))

        return seg, boundary

def train(model, loader, device, epochs=20):

    optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min')

    model.to(device)

    for epoch in range(epochs):

        model.train()

        total_loss = 0
        dice_vals, iou_vals = [], []

        for img, mask, boundary in loader:

            img, mask, boundary = img.to(device), mask.to(device), boundary.to(device)

            optimizer.zero_grad()

            pred_mask, pred_boundary = model(img)

            loss = compute_loss(pred_mask, pred_boundary, mask, boundary)

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

            dice_vals.append(dice_score(pred_mask, mask).item())
            iou_vals.append(iou_score(pred_mask, mask).item())

        avg_loss = total_loss / len(loader)
        scheduler.step(avg_loss)

        print(f"Epoch {epoch} | Loss {avg_loss:.4f} | Dice {sum(dice_vals)/len(dice_vals):.4f} | IoU {sum(iou_vals)/len(iou_vals):.4f}")

def dice_loss(pred, target, eps=1e-6):
    pred = pred.view(-1)
    target = target.view(-1)

    intersection = (pred * target).sum()
    return 1 - (2 * intersection + eps) / (pred.sum() + target.sum() + eps)


def compute_loss(pred_mask, pred_boundary, mask, boundary):

    bce_mask = F.binary_cross_entropy(pred_mask, mask)
    bce_boundary = F.binary_cross_entropy(pred_boundary, boundary)

    d_loss = dice_loss(pred_mask, mask)

    return 0.6 * bce_mask + 0.3 * d_loss + 0.1 * bce_boundary

def dice_score(pred, target, eps=1e-6):
    pred = (pred > 0.5).float()

    pred = pred.view(-1)
    target = target.view(-1)

    return (2 * (pred * target).sum() + eps) / (pred.sum() + target.sum() + eps)


def iou_score(pred, target, eps=1e-6):
    pred = (pred > 0.5).float()

    pred = pred.view(-1)
    target = target.view(-1)

    intersection = (pred * target).sum()
    union = pred.sum() + target.sum() - intersection

    return (intersection + eps) / (union + eps)

img_dir = "/content/cryonuseg/tissue images"
mask_dir = "/content/cryonuseg/Annotator 1 (biologist second round of manual marks up)/Annotator 1 (biologist second round of manual marks up)/label masks"

img_paths = sorted(glob(os.path.join(img_dir, "*")))
mask_paths = sorted(glob(os.path.join(mask_dir, "**", "*"), recursive=True))

mask_dict = {os.path.splitext(os.path.basename(p))[0]: p for p in mask_paths}

paired_imgs = []
paired_masks = []

for p in img_paths:
    name = os.path.splitext(os.path.basename(p))[0]
    if name in mask_dict:
        paired_imgs.append(p)
        paired_masks.append(mask_dict[name])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = ResNetUNet().to(device)

"""### Adding Validation and Early Stopping to CryoNuSeg Training

To improve the training process and prevent overfitting, a validation loop with early stopping will be added. This involves:

1.  **Splitting the dataset**: Dividing the available CryoNuSeg data into training and validation sets.
2.  **Validation function**: Creating a function to evaluate the model's performance on the validation set after each epoch.
3.  **Early stopping**: Monitoring the validation loss and stopping training if it doesn't improve for a certain number of epochs (`patience`).
4.  **Saving the best model**: Storing the model weights that achieved the lowest validation loss.
"""

from sklearn.model_selection import train_test_split

# Assuming paired_imgs and paired_masks are already defined from previous cells
# e.g., from cell 5nr1GoLR1Uvb

train_imgs_cryo, val_imgs_cryo, train_masks_cryo, val_masks_cryo = train_test_split(
    paired_imgs,
    paired_masks,
    test_size=0.2,
    random_state=42 # for reproducibility
)

print(f"CryoNuSeg Training samples: {len(train_imgs_cryo)}")
print(f"CryoNuSeg Validation samples: {len(val_imgs_cryo)}")

from torch.utils.data import DataLoader

# Create datasets and dataloaders for training and validation
train_dataset_cryo = CryoNuSegDataset(train_imgs_cryo, train_masks_cryo)
val_dataset_cryo = CryoNuSegDataset(val_imgs_cryo, val_masks_cryo)

train_loader_cryo = DataLoader(train_dataset_cryo, batch_size=4, shuffle=True)
val_loader_cryo = DataLoader(val_dataset_cryo, batch_size=4, shuffle=False)

print(f"CryoNuSeg Training loader batches: {len(train_loader_cryo)}")
print(f"CryoNuSeg Validation loader batches: {len(val_loader_cryo)}")

from PIL import Image
import matplotlib.pyplot as plt

def show_batch_range(X, Y, start=0, end=6):

    end = min(end, len(X))

    n = end - start

    plt.figure(figsize=(10, 2 * n))

    for i, idx in enumerate(range(start, end)):

        img = X[idx]
        mask = Y[idx]

        plt.subplot(n, 2, 2*i + 1)
        plt.imshow(img)
        plt.title(f"Image {idx}")
        plt.axis("off")

        plt.subplot(n, 2, 2*i + 2)
        plt.imshow(mask, cmap="gray")
        plt.title(f"Mask {idx}")
        plt.axis("off")

    plt.tight_layout()
    plt.show()

X_data = []
Y_data = []

# Get preprocessed images and masks from the dataset
for i in range(4): # Loop for the first 4 samples as requested by end=4
    img_tensor, mask_tensor, _ = train_dataset_cryo[i]

    # Convert PyTorch tensors to NumPy arrays and adjust dimensions for matplotlib
    X_data.append(img_tensor.permute(1, 2, 0).numpy()) # (C, H, W) -> (H, W, C)
    Y_data.append(mask_tensor.squeeze(0).numpy())    # (1, H, W) -> (H, W)

show_batch_range(X_data, Y_data, start=0, end=4)

def validate_cryo(model, loader, device):
    model.eval()
    total_loss = 0
    dice_vals = []
    iou_vals = []

    with torch.no_grad():
        for img, mask, boundary in loader:
            img, mask, boundary = img.to(device), mask.to(device), boundary.to(device)

            pred_mask, pred_boundary = model(img)

            # Use the CryoNuSeg specific compute_loss
            loss = compute_loss(pred_mask, pred_boundary, mask, boundary)

            total_loss += loss.item()

            dice_vals.append(dice_score(pred_mask, mask).item())
            iou_vals.append(iou_score(pred_mask, mask).item())

    avg_loss = total_loss / len(loader)
    avg_dice = sum(dice_vals) / len(dice_vals)
    avg_iou = sum(iou_vals) / len(iou_vals)

    return avg_loss, avg_dice, avg_iou

def train_cryo_earlystop(model, train_loader, val_loader, device, epochs=30, patience=5):

    optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min', factor=0.5, patience=2)

    best_val_loss = float('inf')
    early_stopping_counter = 0

    model.to(device)

    for epoch in range(epochs):

        # Training loop
        model.train()
        train_total_loss = 0
        train_dice_vals, train_iou_vals = [], []

        for img, mask, boundary in train_loader:
            img, mask, boundary = img.to(device), mask.to(device), boundary.to(device)

            optimizer.zero_grad()

            pred_mask, pred_boundary = model(img)

            loss = compute_loss(pred_mask, pred_boundary, mask, boundary)

            loss.backward()
            optimizer.step()

            train_total_loss += loss.item()

            train_dice_vals.append(dice_score(pred_mask, mask).item())
            train_iou_vals.append(iou_score(pred_mask, mask).item())

        avg_train_loss = train_total_loss / len(train_loader)
        avg_train_dice = sum(train_dice_vals) / len(train_dice_vals)
        avg_train_iou = sum(train_iou_vals) / len(train_iou_vals)

        # Validation loop
        val_loss, val_dice, val_iou = validate_cryo(model, val_loader, device)

        scheduler.step(val_loss)

        print(
            f"Epoch {epoch+1}/{epochs} | "
            f"Train Loss: {avg_train_loss:.4f} | Train Dice: {avg_train_dice:.4f} | Train IoU: {avg_train_iou:.4f} | "
            f"Val Loss: {val_loss:.4f} | Val Dice: {val_dice:.4f} | Val IoU: {val_iou:.4f}"
        )

        # Early stopping logic
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            early_stopping_counter = 0
            torch.save(model.state_dict(), "best_cryo_model.pth")
            print("✅ Best model saved.")
        else:
            early_stopping_counter += 1
            print(f"⚠️ Validation loss did not improve ({{early_stopping_counter}}/{{patience}})")

        if early_stopping_counter >= patience:
            print("🛑 Early stopping triggered.")
            break

    print("Training finished.")

# Initialize a new model to ensure a clean slate before training with early stopping
model_cryo_es = ResNetUNet()
model_cryo_es.to(device)

# Start training with validation and early stopping
train_cryo_earlystop(
    model_cryo_es,
    train_loader_cryo,
    val_loader_cryo,
    device,
    epochs=30, # Increased epochs as early stopping will handle termination
    patience=5
)

# Evaluate the best model on the test set (if available, otherwise on a separate evaluation set)
# For now, let's load the best model and evaluate on the validation set for demonstration

# Load the best model state
best_model_cryo = ResNetUNet()
best_model_cryo.load_state_dict(torch.load("best_cryo_model.pth"))
best_model_cryo.to(device)

print("\n--- Evaluation of Best CryoNuSeg Model ---")
val_loss, val_dice, val_iou = validate_cryo(best_model_cryo, val_loader_cryo, device)
print(f"Final Validation Loss: {val_loss:.4f} | Final Validation Dice: {val_dice:.4f} | Final Validation IoU: {val_iou:.4f}")

x = torch.randn(2, 3, 256, 256).to(device)
y = model(x)
print(y[0].shape, y[1].shape)

#torch.save(model.state_dict(), "cryo_full_model.pth")

"""STAGE 2"""

import os
import cv2
import numpy as np
from glob import glob
from PIL import Image
import torch
from torch.utils.data import Dataset

import os
from glob import glob

def match_images_masks(img_dir, mask_dir):

    img_paths = sorted(glob(os.path.join(img_dir, "*")))
    mask_paths = sorted(glob(os.path.join(mask_dir, "*")))

    mask_dict = {
        os.path.splitext(os.path.basename(p))[0]: p
        for p in mask_paths
    }

    paired_imgs = []
    paired_masks = []

    for img_path in img_paths:
        name = os.path.splitext(os.path.basename(img_path))[0]

        if name in mask_dict:
            paired_imgs.append(img_path)
            paired_masks.append(mask_dict[name])

    print(f"Images found: {len(img_paths)}")
    print(f"Masks found: {len(mask_paths)}")
    print(f"Paired: {len(paired_imgs)}")

    return paired_imgs, paired_masks

train_img_dir = "/content/monuseg/kmms_training/kmms_training/images"
train_mask_dir = "/content/monuseg/kmms_training/kmms_training/masks"

test_img_dir = "/content/monuseg_clean/test/images"
test_mask_dir = "/content/monuseg_clean/test/masks"


train_imgs, train_masks = match_images_masks(train_img_dir, train_mask_dir)
test_imgs, test_masks = match_images_masks(test_img_dir, test_mask_dir)

class MoNuSegDataset(Dataset):

    def __init__(self, img_paths, mask_paths, img_size=256):
        self.img_paths = img_paths
        self.mask_paths = mask_paths
        self.img_size = img_size

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):

        img = cv2.imread(self.img_paths[idx])
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (self.img_size, self.img_size))
        img = img / 255.0

        # Use PIL to read the mask to ensure all values are preserved
        mask = np.array(Image.open(self.mask_paths[idx]))
        mask = cv2.resize(mask, (self.img_size, self.img_size),
                          interpolation=cv2.INTER_NEAREST)

        mask = (mask > 0).astype(np.float32)

        img = torch.tensor(img, dtype=torch.float32).permute(2,0,1)
        mask = torch.tensor(mask, dtype=torch.float32).unsqueeze(0)

        return img, mask

"""Let's visualize a sample from the `MoNuSegDataset` to see the effect of these preprocessing steps."""

train_dataset = MoNuSegDataset(train_imgs, train_masks, img_size=256)
test_dataset  = MoNuSegDataset(test_imgs, test_masks, img_size=256)

import matplotlib.pyplot as plt
import numpy as np

def visualize_monuseg_sample(dataset, idx=0):
    img, mask = dataset[idx]

    # Convert tensors to numpy arrays for plotting
    img_np = img.permute(1, 2, 0).numpy()  # C, H, W -> H, W, C
    mask_np = mask.squeeze().numpy()      # 1, H, W -> H, W

    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    axes[0].imshow(img_np)
    axes[0].set_title("Processed Image (Normalized, RGB)")
    axes[0].axis("off")

    axes[1].imshow(mask_np, cmap="gray")
    axes[1].set_title("Processed Mask (Resized, Binarized)")
    axes[1].axis("off")

    plt.tight_layout()
    plt.show()

visualize_monuseg_sample(train_dataset, idx=0)

import torchvision.transforms.functional as TF
import random

def light_aug(img, mask):

    if random.random() > 0.5:
        img = TF.hflip(img)
        mask = TF.hflip(mask)

    if random.random() > 0.5:
        img = TF.vflip(img)
        mask = TF.vflip(mask)

    return img, mask

model = ResNetUNet().to(device)
model.load_state_dict(torch.load("/content/best_cryo_model.pth", map_location=device))

for name, param in model.named_parameters():
    if "enc" in name:
        param.requires_grad = False

import torch.nn.functional as F

def dice_loss(pred, target, eps=1e-6):

    pred = pred.view(-1)
    target = target.view(-1)

    intersection = (pred * target).sum()

    return 1 - (2 * intersection + eps) / (pred.sum() + target.sum() + eps)


def compute_loss(pred, mask):
    bce = F.binary_cross_entropy(pred, mask)
    dice = dice_loss(pred, mask)
    return 0.5 * bce + 0.5 * dice

def dice_score(pred, target, eps=1e-6):
    pred = (pred > 0.5).float()

    pred = pred.view(-1)
    target = target.view(-1)

    return (2 * (pred * target).sum() + eps) / (pred.sum() + target.sum() + eps)


def iou_score(pred, target, eps=1e-6):
    pred = (pred > 0.5).float()

    pred = pred.view(-1)
    target = target.view(-1)

    inter = (pred * target).sum()
    union = pred.sum() + target.sum() - inter

    return (inter + eps) / (union + eps)

"""early stop"""

import os
import cv2
import numpy as np
from glob import glob
from PIL import Image
import torch
from torch.utils.data import Dataset

import os
from glob import glob

def match_images_masks(img_dir, mask_dir):

    img_paths = sorted(glob(os.path.join(img_dir, "*")))
    mask_paths = sorted(glob(os.path.join(mask_dir, "*")))

    mask_dict = {
        os.path.splitext(os.path.basename(p))[0]: p
        for p in mask_paths
    }

    paired_imgs = []
    paired_masks = []

    for img_path in img_paths:
        name = os.path.splitext(os.path.basename(img_path))[0]

        if name in mask_dict:
            paired_imgs.append(img_path)
            paired_masks.append(mask_dict[name])

    print(f"Images found: {len(img_paths)}")
    print(f"Masks found: {len(mask_paths)}")
    print(f"Paired: {len(paired_imgs)}")

    return paired_imgs, paired_masks

train_img_dir = "/content/monuseg/kmms_training/kmms_training/images"
train_mask_dir = "/content/monuseg/kmms_training/kmms_training/masks"

test_img_dir = "/content/monuseg_clean/test/images"
test_mask_dir = "/content/monuseg_clean/test/masks"


train_imgs, train_masks = match_images_masks(train_img_dir, train_mask_dir)
test_imgs, test_masks = match_images_masks(test_img_dir, test_mask_dir)

from sklearn.model_selection import train_test_split

train_imgs_split, val_imgs_split, train_masks_split, val_masks_split = train_test_split(
    train_imgs,
    train_masks,
    test_size=0.2,
    random_state=42
)

print("Train:", len(train_imgs_split))
print("Validation:", len(val_imgs_split))

train_dataset = MoNuSegDataset(
    train_imgs_split,
    train_masks_split,
    img_size=256
)

val_dataset = MoNuSegDataset(
    val_imgs_split,
    val_masks_split,
    img_size=256
)

train_loader = DataLoader(
    train_dataset,
    batch_size=4,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=4,
    shuffle=False
)

batch = next(iter(train_loader))
print(type(batch))
print(len(batch))

def validate(model, loader, device):

    model.eval()

    total_loss = 0
    dice_vals = []
    iou_vals = []

    with torch.no_grad():

        for img, mask in loader:

            img = img.to(device)
            mask = mask.to(device)

            pred, _ = model(img)

            loss = compute_loss(pred, mask)

            total_loss += loss.item()

            dice_vals.append(dice_score(pred, mask).item())
            iou_vals.append(iou_score(pred, mask).item())

    avg_loss = total_loss / len(loader)
    avg_dice = sum(dice_vals) / len(dice_vals)
    avg_iou = sum(iou_vals) / len(iou_vals)

    return avg_loss, avg_dice, avg_iou

def train_monus_earlystop(
    model,
    train_loader,
    val_loader,
    device,
    epochs=30,
    patience=5
):

    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=1e-5,
        weight_decay=1e-4
    )

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode='min',
        factor=0.5,
        patience=2
    )

    best_val_loss = float("inf")
    early_counter = 0

    for epoch in range(epochs):

        # ======================
        # TRAIN
        # ======================

        model.train()

        train_loss = 0
        train_dice = []
        train_iou = []

        for img, mask in train_loader:

            img = img.to(device)
            mask = mask.to(device)

            optimizer.zero_grad()

            pred, _ = model(img)

            loss = compute_loss(pred, mask)

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                1.0
            )

            optimizer.step()

            train_loss += loss.item()

            train_dice.append(
                dice_score(pred, mask).item()
            )

            train_iou.append(
                iou_score(pred, mask).item()
            )

        avg_train_loss = train_loss / len(train_loader)

        # ======================
        # VALIDATION
        # ======================

        val_loss, val_dice, val_iou = validate(
            model,
            val_loader,
            device
        )

        scheduler.step(val_loss)

        print(
            f"Epoch {epoch} | "
            f"Train Loss: {avg_train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val Dice: {val_dice:.4f} | "
            f"Val IoU: {val_iou:.4f}"
        )

        # ======================
        # SAVE BEST MODEL
        # ======================

        if val_loss < best_val_loss:

            best_val_loss = val_loss
            early_counter = 0

            torch.save(
                model.state_dict(),
                "best_monu_model.pth"
            )

            print("✅ Best model updated.")

        else:

            early_counter += 1

            print(
                f"⚠️ No improvement ({early_counter}/{patience})"
            )

        # ======================
        # EARLY STOPPING
        # ======================

        if early_counter >= patience:

            print("🛑 Early stopping triggered.")
            break

train_monus_earlystop(
    model,
    train_loader,
    val_loader,
    device,
    epochs=30,
    patience=5
)

test_dataset = MoNuSegDataset(test_imgs, test_masks)
test_loader = DataLoader(test_dataset, batch_size=4, shuffle=True)

def evaluate(model, loader, device):

    model.eval()

    dice_vals = []
    iou_vals = []

    with torch.no_grad():
        for img, mask in loader:

            img = img.to(device)
            mask = mask.to(device)

            pred, _ = model(img)

            dice_vals.append(dice_score(pred, mask).item())
            iou_vals.append(iou_score(pred, mask).item())

    print("TEST RESULTS")
    print("Dice:", sum(dice_vals)/len(dice_vals))
    print("IoU :", sum(iou_vals)/len(iou_vals))

evaluate(model, test_loader, device)

torch.save(model.state_dict(), "best_monus_model_final.pth")

import matplotlib.pyplot as plt
import numpy as np
import torch

def visualize_predictions(model, loader, device, num_samples=3):

    model.eval()

    with torch.no_grad():

        for idx, (img, mask) in enumerate(loader):

            if idx >= num_samples:
                break

            img = img.to(device)
            mask = mask.to(device)

            pred, _ = model(img)

            pred_bin = (pred > 0.5).float()

            # FIRST SAMPLE IN BATCH
            image = img[0].cpu().permute(1,2,0).numpy()
            gt = mask[0].cpu().squeeze().numpy()
            pr = pred_bin[0].cpu().squeeze().numpy()

            # ERROR MAPS
            false_positive = np.logical_and(pr == 1, gt == 0)
            false_negative = np.logical_and(pr == 0, gt == 1)

            fig, axes = plt.subplots(1, 5, figsize=(22,5))

            axes[0].imshow(image)
            axes[0].set_title("Histology Image")
            axes[0].axis("off")

            axes[1].imshow(gt, cmap="gray")
            axes[1].set_title("Ground Truth")
            axes[1].axis("off")

            axes[2].imshow(pr, cmap="gray")
            axes[2].set_title("Prediction")
            axes[2].axis("off")

            axes[3].imshow(false_positive, cmap="Reds")
            axes[3].set_title("False Positives")
            axes[3].axis("off")

            axes[4].imshow(false_negative, cmap="Blues")
            axes[4].set_title("Missed Nuclei")
            axes[4].axis("off")

            plt.tight_layout()
            plt.show()

visualize_predictions(model, val_loader, device)

visualize_predictions(model, test_loader, device)

"""stage 3"""

import pandas as pd
import os
from PIL import Image
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms

os.listdir("/content/pcam")

os.listdir("/content/pcam/train")
os.listdir("/content/pcam/test")

show_samples("/content/pcam")

"""## Denoising Example for PCam Data"""

import random
import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# Assuming IMG_SIZE is defined in a previous cell or globally
# If not, it needs to be defined, e.g., IMG_SIZE = 256
IMG_SIZE = 96 # PCam images are 96x96

def denoise_sample(img_path, h_img=10, h_color=10, templateWindowSize=7, searchWindowSize=21):
    # Load and preprocess image
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

    # Apply denoising to the image
    denoised_img = cv2.fastNlMeansDenoisingColored(img, None, h_img, h_color, templateWindowSize, searchWindowSize)

    # Assert the image output shape
    assert img.shape == (IMG_SIZE, IMG_SIZE, 3), f"Expected image shape ({IMG_SIZE}, {IMG_SIZE}, 3), but got {img.shape}"
    assert denoised_img.shape == (IMG_SIZE, IMG_SIZE, 3), f"Expected denoised image shape ({IMG_SIZE}, {IMG_SIZE}, 3), but got {denoised_img.shape}"

    return img, denoised_img

# Get a random sample from PCam training set
import pandas as pd

train_labels_df = pd.read_csv("/content/pcam/train_labels.csv")
sample_row = train_labels_df.sample(1)
sample_img_id = sample_row.iloc[0, 0]
sample_img_path = os.path.join("/content/pcam/train", sample_img_id + ".tif")

original_img, denoised_img = denoise_sample(
    sample_img_path
)

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(original_img)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(denoised_img)
plt.title("Denoised Image (NLM)")
plt.axis("off")

plt.tight_layout()
plt.show()

"""Do these denoising effects look appropriate to you for PCam data? If so, we can integrate them into the `PCamDataset` class."""

import pandas as pd
import os
from PIL import Image
from torch.utils.data import Dataset
import cv2
import numpy as np

class PCamDataset(Dataset):

    def __init__(self, csv_file, img_dir, transform=None, img_size=96, apply_denoising=False):

        self.data = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform
        self.img_size = img_size
        self.apply_denoising = apply_denoising

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):

        img_id = self.data.iloc[idx, 0]
        label = self.data.iloc[idx, 1]

        img_path = os.path.join(self.img_dir, img_id + ".tif")

        # Load image using OpenCV
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Resize to native PCam size
        image = cv2.resize(image, (self.img_size, self.img_size))

        if self.apply_denoising:
            # Apply denoising parameters from denoise_sample function
            image = cv2.fastNlMeansDenoisingColored(image, None, 10, 10, 7, 21)

        # Convert numpy array to PIL Image for torchvision transforms
        image = Image.fromarray(image)

        if self.transform:
            image = self.transform(image)

        return image, label

#denoise the pcam dataset

import torchvision.transforms as transforms

transform = transforms.Compose([
    transforms.Resize((96, 96)),  # PCam images are 96x96
    transforms.ToTensor()
])

import matplotlib.pyplot as plt
import numpy as np

# Create a dataset without denoising
pcam_dataset_no_denoise = PCamDataset(
    csv_file="/content/pcam/train_labels.csv",
    img_dir="/content/pcam/train",
    transform=transform,
    apply_denoising=False
)

# Create a dataset with denoising
pcam_dataset_with_denoise = PCamDataset(
    csv_file="/content/pcam/train_labels.csv",
    img_dir="/content/pcam/train",
    transform=transform,
    apply_denoising=True
)

# Get a sample image from each dataset (e.g., the first one)
# Ensure the dataset is not empty before attempting to access an item
if len(pcam_dataset_no_denoise) > 0:
    img_no_denoise, _ = pcam_dataset_no_denoise[0]
    img_with_denoise, _ = pcam_dataset_with_denoise[0]

    # Convert tensor to numpy array for plotting and permute dimensions (C, H, W -> H, W, C)
    img_no_denoise_np = img_no_denoise.permute(1, 2, 0).numpy()
    img_with_denoise_np = img_with_denoise.permute(1, 2, 0).numpy()

    # Plotting
    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(img_no_denoise_np)
    plt.title("PCam Image (No Denoising)")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(img_with_denoise_np)
    plt.title("PCam Image (With Denoising)")
    plt.axis("off")

    plt.tight_layout()
    plt.show()
else:
    print("PCam dataset is empty.")

from torch.utils.data import DataLoader

train_dataset = PCamDataset(
    csv_file="/content/pcam/train_labels.csv",
    img_dir="/content/pcam/train",
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
        num_workers=2
)

"""### PCam Model Definition and Training (ResNet34 Backbone)

The `PCamModel` class is redefined to use a ResNet34 backbone, allowing for transfer learning from the MoNuSeg model. It features a custom classifier head for the binary classification task of PCam images.
"""

import torch
import torch.nn as nn
import torchvision.models as models

class PCamModel(nn.Module):
    def __init__(self):
        super().__init__()

        base = models.resnet34(weights=None)

        # backbone (same as MonuSeg encoder)
        self.features = nn.Sequential(*list(base.children())[:-1])

        self.classifier = nn.Sequential(
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(256, 1)
        )

    def forward(self, x):
        x = self.features(x)
        x = x.flatten(1)
        return self.classifier(x)

"""Focal Loss is used as the criterion to address potential class imbalance in the PCam dataset, focusing training on hard-to-classify examples."""

import torch.nn.functional as F

def focal_loss(logits, targets, alpha=0.75, gamma=2):
    targets = targets.float().unsqueeze(1)

    bce = F.binary_cross_entropy_with_logits(logits, targets, reduction='none')
    prob = torch.sigmoid(logits)

    pt = prob * targets + (1 - prob) * (1 - targets)

    loss = alpha * (1 - pt) ** gamma * bce
    return loss.mean()

"""The evaluation function provides detailed metrics, including sensitivity and specificity, crucial for medical image analysis where false negatives can be particularly costly."""

from sklearn.metrics import confusion_matrix
import numpy as np

def evaluate(model, loader, device, threshold=0.3):
    model.eval()

    probs, labels = [], []

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device)

            logits = model(x)
            p = torch.sigmoid(logits).cpu().numpy()

            probs.extend(p.flatten())
            labels.extend(y.numpy())

    preds = (np.array(probs) > threshold).astype(int)

    cm = confusion_matrix(labels, preds)

    tn, fp, fn, tp = cm.ravel()

    # Handle cases where denominator might be zero
    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

    print("Confusion Matrix:\n", cm)
    print("Sensitivity (Recall cancer):", sensitivity)
    print("Specificity:", specificity)

"""A single epoch training function to encapsulate the training logic for better organization."""

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()

    total_loss = 0

    for imgs, labels in loader:
        imgs = imgs.to(device)
        labels = labels.to(device).float()

        optimizer.zero_grad()

        logits = model(imgs)
        loss = criterion(logits, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)

"""Initialize the `PCamModel` and load the pre-trained weights from the MoNuSeg model into its ResNet34 backbone. This approach leverages knowledge gained from a similar segmentation task to potentially improve performance on PCam classification."""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = PCamModel()

# Load fresh resnet34 weights (ImageNet pre-trained if desired, here None for flexibility)
resnet = models.resnet34(weights=None)
model.features.load_state_dict(resnet.state_dict(), strict=False)

# Load MonuSeg checkpoint
monu_ckpt = torch.load("best_monus_model_final.pth", map_location="cpu")

# Filter MonuSeg weights that match the PCamModel's feature extractor
model_dict = model.features.state_dict()
filtered = {
    k: v for k, v in monu_ckpt.items()
    if k in model_dict and model_dict[k].shape == v.shape
}

# Load filtered weights into the model's feature extractor
model.features.load_state_dict(filtered, strict=False)

model = model.to(device)
print("PCamModel initialized and MonuSeg weights loaded into backbone.")

"""Initially, freeze the backbone (feature extractor) to train only the classifier head. This is a common practice in transfer learning to adapt the pre-trained model to the new task without drastically altering its learned features."""

for param in model.features.parameters():
    param.requires_grad = False

print("Backbone frozen.")

"""Define the criterion (`focal_loss`) and optimizer for the classifier head. Only the classifier's parameters are updated since the backbone is frozen."""

criterion = focal_loss
optimizer = torch.optim.AdamW(model.classifier.parameters(), lr=1e-4)
print("Criterion and Optimizer for classifier defined.")

"""Train the model for a few epochs, focusing on the classifier. This fine-tunes the output layer to the PCam dataset."""

import os

test_images_path = '/content/pcam/test'
total_test_images = len(os.listdir(test_images_path))
print(f"Total images in PCam test dataset: {total_test_images}")

import os

train_images_path = '/content/pcam/train'
total_train_images = len(os.listdir(test_images_path))
print(f"Total images in PCam train dataset: {total_train_images}")

"""### Class Imbalance in PCam Train Dataset"""

import torchvision.transforms as transforms
from torch.utils.data import DataLoader, random_split
import numpy as np
from sklearn.metrics import confusion_matrix

# Define the transformation for PCam images
transform = transforms.Compose([
    transforms.Resize((96, 96)),
    transforms.ToTensor()
])

# Instantiate the full PCam dataset from train_labels.csv
full_pcam_dataset = PCamDataset(
    csv_file="/content/pcam/train_labels.csv",
    img_dir="/content/pcam/train",
    transform=transform,
    apply_denoising=False # Set to True if denoising is desired
)

# Perform a train-validation split (e.g., 80% train, 20% validation)
train_size = int(0.8 * len(full_pcam_dataset))
val_size = len(full_pcam_dataset) - train_size
pc_train_subset, pc_val_subset = random_split(full_pcam_dataset, [train_size, val_size])

# Create PCam DataLoaders for training and validation
pc_train_loader = DataLoader(
    pc_train_subset,
    batch_size=64,
    shuffle=True,
    num_workers=0 # Changed from 2 to 0 to prevent multiprocessing error
)
pc_val_loader = DataLoader(
    pc_val_subset,
    batch_size=64, # Use appropriate batch size for testing
    shuffle=False,
    num_workers=0 # Changed from 2 to 0 to prevent multiprocessing error
)

import pandas as pd
import numpy as np

# Load the original train labels
train_labels_df = pd.read_csv("/content/pcam/train_labels.csv")

print("Class distribution for the full PCam training dataset:")
display(train_labels_df['label'].value_counts(normalize=True))

# Assuming pcam_train_subset and pcam_val_subset are already defined from cell 4f104396
# Extract labels from the training subset
train_labels_split = [full_pcam_dataset.data.iloc[i, 1] for i in pcam_train_subset.indices]
val_labels_split = [full_pcam_dataset.data.iloc[i, 1] for i in pcam_val_subset.indices]

print("\nClass distribution for the PCam training subset after split:")
display(pd.Series(train_labels_split).value_counts(normalize=True))

print("\nClass distribution for the PCam validation subset after split:")
display(pd.Series(val_labels_split).value_counts(normalize=True))

import pandas as pd
display(pd.Series(val_labels_split).value_counts(normalize=True))

# Define a validation function for PCam
def validate_pcam(model, loader, criterion, device, threshold=0.5):
    model.eval()
    total_loss = 0
    all_probs, all_labels = [], []

    with torch.no_grad():
        for imgs, labels in loader:
            imgs = imgs.to(device)
            labels = labels.to(device).float()

            logits = model(imgs)
            loss = criterion(logits, labels)
            total_loss += loss.item()

            p = torch.sigmoid(logits).cpu().numpy()
            all_probs.extend(p.flatten())
            all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader)
    preds = (np.array(all_probs) > threshold).astype(int)

    cm = confusion_matrix(all_labels, preds)
    # Unpack confusion matrix, handling cases where a class might be missing
    tn, fp, fn, tp = cm.ravel() if cm.size == 4 else (0,0,0,0) # Default to zeros if CM is not 2x2

    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

    return avg_loss, sensitivity, specificity, cm

epochs = 10

print("Training classifier head...")
for epoch in range(epochs):
    train_loss = train_one_epoch(model, pcam_train_loader, optimizer, criterion, device)
    val_loss, val_sensitivity, val_specificity, _ = validate_pcam(model, pcam_val_loader, criterion, device)
    print(f"Epoch {epoch} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val Sensitivity: {val_sensitivity:.4f} | Val Specificity: {val_specificity:.4f}")

"""Evaluate the model's performance on the test set using the detailed evaluation function."""

print("Evaluating model performance on the validation set (as no independent test set with labels is available yet)...")
# Use the validate_pcam function and pcam_val_loader defined earlier for PCam evaluation
val_loss, val_sensitivity, val_specificity, cm = validate_pcam(model, pcam_val_loader, criterion, device, threshold=0.3)
print(f"Validation Loss: {val_loss:.4f} | Validation Sensitivity: {val_sensitivity:.4f} | Validation Specificity: {val_specificity:.4f}")
print("Confusion Matrix:\n", cm)

"""After initial training of the classifier, unfreeze the backbone for further fine-tuning. This allows the entire model to adapt to the PCam data."""

for param in model.features.parameters():
    param.requires_grad = True

optimizer_full = torch.optim.AdamW(model.parameters(), lr=1e-5)
print("Backbone unfrozen and new optimizer for full model defined.")

"""Continue training with the unfrozen backbone, using a lower learning rate to prevent large changes to the pre-trained weights."""

epochs_fine_tune = 3

print("Fine-tuning full model...")
for epoch in range(epochs_fine_tune):
    train_loss = train_one_epoch(model, pc_train_loader, optimizer_full, criterion, device)
    print(f"Fine-tune Epoch {epoch} | Train Loss: {train_loss:.4f}")

"""Final evaluation after fine-tuning the entire model."""

print("Final evaluation after fine-tuning:")
evaluate(model, pcam_val_loader, device, threshold=0.3)

torch.save(model.state_dict(), "best_pcam_model_final.pth")

import torch
from sklearn.metrics import roc_auc_score

def evaluate_auc(model, loader, device):

    model.eval()

    all_preds = []
    all_labels = []

    with torch.no_grad():

        for img, label in loader:

            img = img.to(device).float()
            label = label.to(device).float()

            logits = model(img)
            probs = torch.sigmoid(logits)

            all_preds.extend(probs.cpu().numpy())
            all_labels.extend(label.cpu().numpy())

    auc = roc_auc_score(all_labels, all_preds)

    print(f"ROC-AUC: {auc:.4f}")

    return auc

evaluate_auc(model, pcam_val_loader, device)

from sklearn.metrics import confusion_matrix
import numpy as np

def evaluate_confusion(model, loader, device, threshold=0.5):

    model.eval()

    preds = []
    labels = []

    with torch.no_grad():

        for img, label in loader:

            img = img.to(device).float()

            logits = model(img)
            probs = torch.sigmoid(logits)

            preds.extend((probs.cpu().numpy() > threshold).astype(int))
            labels.extend(label.numpy())

    cm = confusion_matrix(labels, preds)

    print("Confusion Matrix:\n", cm)

    return cm

evaluate_confusion(model, pcam_val_loader, device)

def find_best_threshold(model, loader, device):

    model.eval()

    probs_all = []
    labels_all = []

    with torch.no_grad():

        for img, label in loader:

            img = img.to(device).float()

            logits = model(img)
            probs = torch.sigmoid(logits)

            probs_all.extend(probs.cpu().numpy())
            labels_all.extend(label.numpy())

    best_t = 0.5
    best_acc = 0

    for t in np.arange(0.1, 0.9, 0.05):

        preds = (np.array(probs_all) > t).astype(int)

        acc = (preds == np.array(labels_all)).mean()

        if acc > best_acc:
            best_acc = acc
            best_t = t

    print(f"Best threshold: {best_t:.2f}, Accuracy: {best_acc:.4f}")

    return best_t

best_threshold = find_best_threshold(model, pcam_val_loader, device)

"""### Transfer Learning for PCam using MoNuSeg Pre-trained Weights

Following the pipeline you described, the PCam model leverages transfer learning from the MoNuSeg segmentation task. This is achieved by initializing the `PCamModel` with a ResNet34 backbone and then loading the weights from the best performing MoNuSeg model (`best_monus_model_final.pth`) into this backbone.

The `PCamModel` is defined in cell `0acb17ab`. It consists of a ResNet34 backbone (feature extractor) and a custom classification head.

The next step, implemented in cell `44a57d79`, initializes the `PCamModel` and then carefully loads the weights from the `best_monus_model_final.pth` into its feature extraction layers (the ResNet34 backbone). This transfers the knowledge gained from the segmentation task to the classification task.

Initially, the backbone parameters are frozen (cell `5c56021d`), allowing only the newly added classification head to be trained. This helps to quickly adapt the model to the PCam classification task while preserving the powerful features learned during MoNuSeg training. The criterion and optimizer for this stage are defined in cell `973a32c2` and the training occurs in cell `4f104396`.

After initial training of the classifier head, the entire model (including the backbone) is unfrozen (cell `05571fda`) and fine-tuned with a lower learning rate (cell `ebd32f07`). This allows the entire network to adapt more specifically to the PCam dataset, potentially leading to further performance improvements.

# PCAM model
"""



"""### Grad-CAM Implementation for PCam Model

Grad-CAM (Gradient-weighted Class Activation Mapping) is a technique for producing visual explanations for decisions from a Convolutional Neural Network. It helps understand which parts of an input image are important for the model's classification decision.

The `PCamModel` uses a ResNet34 backbone as its feature extractor (encoder). This is an appropriate architecture for Grad-CAM as it contains convolutional layers whose activations and gradients can be used to generate heatmaps.
"""

import torch
import torch.nn.functional as F
import numpy as np
import cv2

class GradCAM:
    def __init__(self, model, target_layer, device):
        self.model = model
        self.target_layer = target_layer
        self.device = device
        self.model.eval()

        self.gradients = None
        self.activations = None

        # Register hooks
        self.target_layer.register_forward_hook(self.save_activation)
        self.target_layer.register_backward_hook(self.save_gradient)

    def save_activation(self, module, input, output):
        self.activations = output

    def save_gradient(self, module, grad_input, grad_output):
        self.gradients = grad_output[0]

    def __call__(self, input_tensor, target_class=None):
        self.model.zero_grad()

        # Forward pass
        output = self.model(input_tensor.to(self.device))

        if target_class is None:
            # For a single-output binary model, if target_class is not specified,
            # we can infer it from the prediction or default to the positive class.
            # Here, we default to the positive class (1) for Grad-CAM if not provided.
            target_class = 1 if torch.sigmoid(output).item() > 0.5 else 0 # Predicting based on 0.5 threshold

        # Create a gradient tensor for the backward pass
        grad_tensor = torch.zeros_like(output).to(self.device)

        if target_class == 1:
            # For the positive class, we want gradients of the output logit
            grad_tensor.fill_(1.0)
        elif target_class == 0:
            # For the negative class, we want gradients of the inverse of the output logit
            # This can be achieved by negating the gradient for the positive logit
            grad_tensor.fill_(-1.0)
        else:
            raise ValueError("For binary classification with single output, target_class must be 0 or 1.")

        output.backward(gradient=grad_tensor, retain_graph=True)

        # Get gradients and activations
        gradients = self.gradients.cpu().data.numpy()
        activations = self.activations.cpu().data.numpy()

        # Pool the gradients across the channels to get per-channel weights
        weights = np.mean(gradients, axis=(2, 3))[0, :]

        # Weighted combination of activations
        cam = np.zeros(activations.shape[2:], dtype=np.float32)
        for i, w in enumerate(weights):
            cam += w * activations[0, i, :, :]

        # ReLU on the CAM and resize to input image size
        cam = np.maximum(cam, 0)
        # Add a small epsilon to denominator to prevent division by zero for completely black heatmaps
        cam_max = np.max(cam)
        if cam_max == 0:
            cam = np.zeros_like(cam)
        else:
            cam = cam / (cam_max + 1e-8)

        cam = cv2.resize(cam, (input_tensor.shape[3], input_tensor.shape[2]))

        return cam

"""### Using Grad-CAM with PCamModel

To use the `GradCAM` class, we need to specify the model, the target convolutional layer (which acts as the encoder's output layer), and the device. For `PCamModel`, the `model.features` (ResNet34 backbone) contains several layers. A common choice for Grad-CAM is the last convolutional layer before the global average pooling, which is `model.features[7]` (equivalent to `resnet.layer4` in the original ResNet34 structure).

Below is an example of how to apply Grad-CAM to a sample PCam image and visualize the heatmap. We will retrieve a sample image from the validation set, and then generate and overlay the heatmap.
"""

# Load the best fine-tuned PCamModel
# Assuming 'model' is the fine-tuned PCamModel loaded and moved to device

# Instantiate GradCAM
# The target layer is typically the last convolutional layer of the feature extractor
# For the ResNet34 backbone used in PCamModel, this corresponds to model.features[7] (which is resnet.layer4)
grad_cam = GradCAM(model=model, target_layer=model.features[7], device=device)

# Get a sample image from the PCam validation loader
# (Assuming pcam_val_loader and pcam_val_subset are already defined)

# Choose a sample from the validation dataset
sample_idx = 0
img_tensor, label = pcam_val_subset[sample_idx]

# Reshape image tensor for model input (add batch dimension) and ensure float type
input_tensor_gradcam = img_tensor.unsqueeze(0).float()

# Get the heatmap
# target_class=1 for cancer (positive class), 0 for negative
# We'll use the predicted class if not specified, or force 1 to see cancer activation
heatmap = grad_cam(input_tensor_gradcam, target_class=1)

# Visualize the heatmap
img_np = img_tensor.permute(1, 2, 0).cpu().numpy()

# Normalize image for display
img_np = (img_np - img_np.min()) / (img_np.max() - img_np.min() + 1e-8) # Added epsilon to prevent division by zero

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(img_np)
plt.title(f"Original Image (Label: {label})")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(img_np)
plt.imshow(heatmap, cmap='jet', alpha=0.5) # Overlay heatmap
plt.title(f"Grad-CAM Heatmap (Target Class: 1)")
plt.axis('off')

plt.tight_layout()
plt.show()



"""### Visualize Grad-CAM Heatmaps for a Batch of PCam Validation Images"""

import matplotlib.pyplot as plt
import numpy as np
import torch
import cv2

def visualize_grad_cam_batch(model, loader, grad_cam_instance, device, num_samples=4):
    model.eval()
    samples_processed = 0

    # Remove torch.no_grad() from the outer loop, as gradients are needed for GradCAM
    for imgs, labels in loader:
        if samples_processed >= num_samples:
            break

        # Iterate through each image in the batch
        for i in range(imgs.shape[0]):
            if samples_processed >= num_samples:
                break

            img_tensor = imgs[i].unsqueeze(0)  # Add batch dimension for single image
            true_label = labels[i].item()

            # Ensure the input tensor requires gradients
            img_tensor.requires_grad_(True)

            # Get model prediction for the current image
            logits = model(img_tensor.to(device))
            pred_prob = torch.sigmoid(logits).item()
            predicted_label = 1 if pred_prob > 0.5 else 0

            # Generate heatmap for the predicted class
            heatmap = grad_cam_instance(img_tensor, target_class=predicted_label)

            # Convert tensor to numpy for plotting
            # Use .detach().cpu().numpy() to get numpy array from tensor that required grad
            img_np = img_tensor.squeeze(0).detach().permute(1, 2, 0).cpu().numpy()

            # Normalize image for display
            img_np = (img_np - img_np.min()) / (img_np.max() - img_np.min() + 1e-8)

            plt.figure(figsize=(10, 5))

            plt.subplot(1, 2, 1)
            plt.imshow(img_np)
            plt.title(f"Original Image (True: {true_label}, Pred: {predicted_label:.0f})")
            plt.axis('off')

            plt.subplot(1, 2, 2)
            plt.imshow(img_np)
            plt.imshow(heatmap, cmap='jet', alpha=0.5)  # Overlay heatmap
            plt.title(f"Grad-CAM Heatmap (Pred: {predicted_label:.0f})")
            plt.axis('off')

            plt.tight_layout()
            plt.show()
            samples_processed += 1

# Assuming `model` is your fine-tuned PCamModel and `grad_cam` is your GradCAM instance
# (from cell `600877b8`) and `pcam_val_loader` is your validation DataLoader.
visualize_grad_cam_batch(model, pcam_val_loader, grad_cam, device, num_samples=4)

"""### Visualize More Grad-CAM Heatmaps for Comparison

Visualizing additional samples helps in understanding the model's behavior across different cases, especially for both positive and negative predictions.
"""

visualize_grad_cam_batch(model, pcam_val_loader, grad_cam, device, num_samples=8)



"""### Quantifying Grad-CAM Focus

To quantify the model's Grad-CAM focus, we can analyze the intensity of the generated heatmaps. A simple approach is to calculate the average heatmap intensity in regions where the heatmap values exceed a certain threshold. This provides a numerical metric for how strongly the model's attention is concentrated on specific areas for its predictions.

The following function `quantify_grad_cam_focus` will:
1. Take a batch of images, their true labels, and the generated heatmaps.
2. For each sample, it will determine the predicted class.
3. It will then calculate the mean intensity of the heatmap in areas where the heatmap value is above a specified threshold.
4. These metrics will be collected and presented to give an insight into the model's focus.
"""

def quantify_grad_cam_focus(model, loader, grad_cam_instance, device, heatmap_threshold=0.5, num_samples=10):
    model.eval()
    # Store a list of dictionaries, each containing details for one sample
    all_sample_results = []
    samples_processed = 0

    for imgs, labels in loader:
        if samples_processed >= num_samples:
            break

        for i in range(imgs.shape[0]):
            if samples_processed >= num_samples:
                break

            img_tensor = imgs[i].unsqueeze(0)  # Add batch dimension for single image
            true_label = labels[i].item()

            # Enable gradients for the input tensor for GradCAM calculation
            # Temporarily clone the tensor to allow requires_grad_ for GradCAM
            img_tensor_for_gradcam = img_tensor.clone().detach().requires_grad_(True)


            # Get model prediction for the current image
            logits = model(img_tensor_for_gradcam.to(device))
            pred_prob = torch.sigmoid(logits).item()
            predicted_label = 1 if pred_prob > 0.5 else 0

            # Generate heatmap for the predicted class
            heatmap = grad_cam_instance(img_tensor_for_gradcam, target_class=predicted_label)

            # Quantify focus: average intensity where heatmap is above threshold
            focused_regions_intensity = heatmap[heatmap > heatmap_threshold]
            if focused_regions_intensity.size > 0:
                avg_focus_intensity = np.mean(focused_regions_intensity)
            else:
                avg_focus_intensity = 0.0 # No regions above threshold

            all_sample_results.append({
                "focus_intensity": avg_focus_intensity,
                "img_tensor": img_tensor.cpu(), # Store on CPU to avoid GPU memory issues for many samples
                "true_label": true_label,
                "predicted_label": predicted_label,
                "heatmap": heatmap # Store the raw heatmap
            })

            samples_processed += 1

    # Print summary statistics as before
    positive_focus_intensities = [res["focus_intensity"] for res in all_sample_results if res["predicted_label"] == 1]
    negative_focus_intensities = [res["focus_intensity"] for res in all_sample_results if res["predicted_label"] == 0]

    print(f"Quantified Grad-CAM Focus for {samples_processed} samples:")
    if positive_focus_intensities:
        print(f"  Average focus intensity for positive class predictions: {np.mean(positive_focus_intensities):.4f}")
    else:
        print("  No positive class predictions observed.")

    if negative_focus_intensities:
        print(f"  Average focus intensity for negative class predictions: {np.mean(negative_focus_intensities):.4f}")
    else:
        print("  No negative class predictions observed.")

    return all_sample_results

import matplotlib.pyplot as plt
import numpy as np
import torch

# Run the quantification function to get results for more samples for better visualization
# Using pcam_val_loader for consistency and more samples
all_results = quantify_grad_cam_focus(
    model,
    pcam_val_loader,
    grad_cam,
    device,
    heatmap_threshold=0.5,
    num_samples=50 # Increased samples to ensure a good pool for top 5
)

# Sort results by focus intensity in descending order
all_results.sort(key=lambda x: x['focus_intensity'], reverse=True)

print(f"Displaying top 5 images with highest Grad-CAM focus intensity from {len(all_results)} samples.")

# Visualize the top 5 samples
plt.figure(figsize=(15, 10))
for i in range(min(5, len(all_results))):
    sample = all_results[i]
    img_tensor = sample["img_tensor"].squeeze(0) # Remove batch dimension
    heatmap = sample["heatmap"]
    true_label = sample["true_label"]
    predicted_label = sample["predicted_label"]
    focus_intensity = sample["focus_intensity"]

    # Convert tensor to numpy for plotting
    img_np = img_tensor.permute(1, 2, 0).numpy()
    # Normalize image for display
    img_np = (img_np - img_np.min()) / (img_np.max() - img_np.min() + 1e-8)

    plt.subplot(5, 2, 2*i + 1)
    plt.imshow(img_np)
    plt.title(f"Original Image (True: {true_label}, Pred: {predicted_label})\nFocus: {focus_intensity:.4f}")
    plt.axis('off')

    plt.subplot(5, 2, 2*i + 2)
    plt.imshow(img_np)
    plt.imshow(heatmap, cmap='jet', alpha=0.5) # Overlay heatmap
    plt.title(f"Grad-CAM Heatmap (Pred: {predicted_label})")
    plt.axis('off')

plt.tight_layout()
plt.show()



"""## Project Description: Histopathological Image Analysis for Cancer Detection and Segmentation

This project demonstrates a comprehensive workflow for analyzing histopathological images, focusing on nuclear segmentation and breast cancer metastasis detection. It leverages transfer learning, advanced image preprocessing, and explainable AI techniques (Grad-CAM) to build and interpret robust deep learning models.

### Key Features:

*   **Dataset Integration & Preprocessing:** Utilizes three distinct histopathological datasets: `CryoNuSeg` (for cryosectioned H&E images), `MoNuSeg` (for nuclei segmentation in various tissues), and `PCam` (for breast cancer metastasis detection in lymph node sections). Includes custom data loading, cleaning, and augmentation pipelines, with an optional denoising step for PCam images.
*   **Nuclear Segmentation with ResNet-UNet:** Implements and trains a ResNet34-based UNet architecture for precise nuclear segmentation on the `CryoNuSeg` dataset. The model incorporates Dice loss, BCE loss, and a boundary loss component for enhanced segmentation accuracy. Early stopping and validation are used to optimize training.
*   **Transfer Learning for Cancer Detection:** Develops a `PCamModel` utilizing a ResNet34 backbone. This model's backbone is initialized with weights pre-trained on the `MoNuSeg` segmentation task, demonstrating effective transfer learning from a related domain. The model is then fine-tuned on the `PCam` dataset for binary classification of cancer metastases.
*   **Class Imbalance Handling:** Employs Focal Loss as the training criterion for the `PCamModel` to address the inherent class imbalance often found in medical datasets, ensuring the model effectively learns from both positive and negative samples.
*   **Model Evaluation:** Provides comprehensive evaluation metrics for both segmentation (Dice, IoU) and classification (Sensitivity, Specificity, ROC-AUC, Confusion Matrix), allowing for a thorough understanding of model performance.
*   **Explainable AI with Grad-CAM:** Integrates a custom `GradCAM` implementation to visualize the regions of input images that are most influential for the `PCamModel`'s classification decisions. This provides crucial insights into the model's reasoning, enhancing trust and interpretability, especially in medical contexts.
*   **Quantitative Grad-CAM Analysis:** Introduces a method to quantify Grad-CAM focus intensity, providing a numerical measure of how concentrated the model's attention is on specific regions of interest. This aids in understanding and comparing model behavior across different predictions.
"""